# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-names
  labels:
    app: get-names
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-names
  template:
    metadata:
      labels:
        app: get-names
    spec:
      containers:
      - name: get-names
        image: us.icr.io/drsns/getnames:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: DBNAME
          value: namesdb
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

