apiVersion: v1
kind: Service
metadata:
  labels:
    app: get-names
  name: get-names
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: get-names
  type: LoadBalancer