# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-names
  labels:
    app: get-names
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-names
  template:
    metadata:
      labels:
        app: get-names
    spec:
      imagePullSecrets:
      - name: ibmcloud-registry-pull
      containers:
      - name: get-names
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DBNAME
          value: namesdb
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

